### ISSUE TITLE
[Bug]: Test in ci pipeline fails due missing AESExample.exe and RSAExample.exe MacOS and Linux test

### ISSUE THREAD

**Issue by maythamfahmi** [maythamfahmi/CryptoNet#107]
### What happened?

Reference: https://github.com/maythamfahmi/CryptoNet/actions/runs/11418047460/job/31771023469

**In MacOS test, giving following error:**
A bug happened!Failed AESExampleSmokeTest [14 ms]
  Error Message:
   System.ComponentModel.Win32Exception : Failed to start a process with file path 'AESExample.exe'. Target file or working directory doesn't exist, or the provided credentials are invalid.
  ----> System.ComponentModel.Win32Exception : An error occurred trying to start process 'AESExample.exe' with working directory '/var/folders/t_/mmhnh941511_hp2lwh383bp00000gn/T/AESExampleTests.AESExampleSmokeTest-1c259a32-2672-475f-85ce-50945e15264a'. No such file or directory

### Version

3.0.x >= (Coming soon)

### What Operating System are you seeing the problem on?

MacOs, Ubuntu

### Relevant log output

```shell
Test run for /Users/runner/work/CryptoNet/CryptoNet/Examples/Examples.UnitTests/bin/Release/net8.0/Examples.UnitTests.dll (.NETCoreApp,Version=v8.0)
Test run for /Users/runner/work/CryptoNet/CryptoNet/CryptoNet.UnitTests/bin/Release/net8.0/CryptoNet.UnitTests.dll (.NETCoreApp,Version=v8.0)
VSTest version 17.11.1 (arm64)

VSTest version 17.11.1 (arm64)

Starting test execution, please wait...
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
A total of 1 test files matched the specified pattern.
  Failed AESExampleSmokeTest [14 ms]
  Error Message:
   System.ComponentModel.Win32Exception : Failed to start a process with file path 'AESExample.exe'. Target file or working directory doesn't exist, or the provided credentials are invalid.
  ----> System.ComponentModel.Win32Exception : An error occurred trying to start process 'AESExample.exe' with working directory '/var/folders/t_/mmhnh941511_hp2lwh383bp00000gn/T/AESExampleTests.AESExampleSmokeTest-1c259a32-2672-475f-85ce-50945e15264a'. No such file or directory
  Stack Trace:
     at CliWrap.Utils.ProcessEx.Start() in /_/CliWrap/Utils/ProcessEx.cs:line 68
   at CliWrap.Command.ExecuteAsync(CancellationToken forcefulCancellationToken, CancellationToken gracefulCancellationToken) in /_/CliWrap/Command.Execution.cs:line 307
   at CliWrap.Command.ExecuteAsync(CancellationToken cancellationToken) in /_/CliWrap/Command.Execution.cs:line 326
   at CryptoNet.Examples.UnitTests.AESExampleTests.AESExampleSmokeTest() in {CryptoNet}/Examples/Examples.UnitTests/AESExampleTests.cs:line 29
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await[TResult](Func`1 invoke)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass3_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated(ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated[T](Func`1 func)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()
--Win32Exception
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at CliWrap.Utils.ProcessEx.Start() in /_/CliWrap/Utils/ProcessEx.cs:line 56

  Failed RSAExampleSmokeTest [6 ms]
  Error Message:
   System.ComponentModel.Win32Exception : Failed to start a process with file path 'RSAExample.exe'. Target file or working directory doesn't exist, or the provided credentials are invalid.
  ----> System.ComponentModel.Win32Exception : An error occurred trying to start process 'RSAExample.exe' with working directory '/var/folders/t_/mmhnh941511_hp2lwh383bp00000gn/T/9736cc39-a69c-401c-8b9a-bd66541543a0'. No such file or directory
  Stack Trace:
     at CliWrap.Utils.ProcessEx.Start() in /_/CliWrap/Utils/ProcessEx.cs:line 68
   at CliWrap.Command.ExecuteAsync(CancellationToken forcefulCancellationToken, CancellationToken gracefulCancellationToken) in /_/CliWrap/Command.Execution.cs:line 307
   at CliWrap.Command.ExecuteAsync(CancellationToken cancellationToken) in /_/CliWrap/Command.Execution.cs:line 326
   at CryptoNet.Examples.UnitTests.RSAExampleTests.RSAExampleSmokeTest() in {CryptoNet}/Examples/Examples.UnitTests/RSAExampleTests.cs:line 21
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await[TResult](Func`1 invoke)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass3_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated(ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated[T](Func`1 func)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()
--Win32Exception
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at CliWrap.Utils.ProcessEx.Start() in /_/CliWrap/Utils/ProcessEx.cs:line 56


Failed!  - Failed:     2, Passed:     0, Skipped:     0, Total:     2, Duration: 23 ms - Examples.UnitTests.dll (net8.0)
  Failed Encrypt_With_PublicKey_Decrypt_With_PrivateKey_Of_Content_Test [664 ms]
  Error Message:
   System.IO.FileNotFoundException : Could not find file '/Users/runner/work/CryptoNet/CryptoNet/CryptoNet.UnitTests/bin/Release/net8.0/publicKey.pub'.
  Stack Trace:
     at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.ReadAllBytes(String path)
   at CryptoNet.Utils.CryptoNetUtils.LoadFileToBytes(String filename) in /_/CryptoNet/Utils/CryptoNetUtils.cs:line 20
   at CryptoNet.Utils.CryptoNetUtils.LoadFileToString(String filename) in /_/CryptoNet/Utils/CryptoNetUtils.cs:line 25
   at CryptoNet.CryptoNetRsa..ctor(FileInfo fileInfo, Int32 keySize) in /_/CryptoNet/CryptoNetRsa.cs:line 53
   at CryptoNet.UnitTests.CryptoNetRsaTests.Encrypt_With_PublicKey_Decrypt_With_PrivateKey_Of_Content_Test() in {CryptoNet}/CryptoNet.UnitTests/CryptoNetRsaTests.cs:line 193
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)

  Failed Export_Public_Key_For_X509_Certificate_Test [10 ms]
  Error Message:
   System.ArgumentNullException : Value cannot be null. (Parameter 'certificate')
  Stack Trace:
     at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at System.Security.Cryptography.X509Certificates.CertificateExtensionsCommon.GetPrivateKey[T](X509Certificate2 certificate, Predicate`1 matchesConstraints)
   at CryptoNet.Extensions.CryptoNetExtensions.GetParameters(X509Certificate2 certificate, KeyType keyType) in /_/CryptoNet.Extensions/CryptoNetExtensions.cs:line 20
   at CryptoNet.CryptoNetRsa..ctor(X509Certificate2 certificate, KeyType keyType, Int32 keySize) in /_/CryptoNet/CryptoNetRsa.cs:line 68
   at CryptoNet.UnitTests.CryptoNetRsaTests.Export_Public_Key_For_X509_Certificate_Test() in {CryptoNet}/CryptoNet.UnitTests/CryptoNetRsaTests.cs:line 225
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)


Failed!  - Failed:     2, Passed:    32, Skipped:     0, Total:    34, Duration: 2 s - CryptoNet.UnitTests.dll (net8.0)
Error: Process completed with exit code 1.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maythamfahmi** [comment]
I have closed #109 as it fixed part of #110 (#111) but ubuntu has still issue simliar to this bug.

**Comment by maythamfahmi** [comment]
The above issues is also coming intor code coverage pipeline #108

https://github.com/maythamfahmi/CryptoNet/actions/runs/11420388608

**Comment by maythamfahmi** [comment]
Btw if the above code is only windows compatible we can you can use something like, just in case

`if (Environment.OSVersion.Platform == PlatformID.Win32NT)`

**Comment by maythamfahmi** [comment]
FYI i have temporarily put `[Ignore("Temp")]`  attributes, to all examples projects tests, this is due to testing the remain of tests, so it does not fail. but when you start looking at it a bugfix branch you change it back to `[Test]`

**Comment by jwdonahue** [comment]
Your build scripts do not seem to be building the executables. The target for both of the examples is 'exe', but I don't see any indication in the build logs, that those are being built. It does build dll's.  The script is running `dotnet build ...`, I always use `dotnet msbuild ...` in my scripts, but I don't run any builds on other OS's. I prefer msbuild over dotnet build, because it guarantees identical build behaviors, whether I am building in VS or in the cloud. 

As far as I know, there is nothing about either of the examples that limits them to just Windows.

**Comment by maythamfahmi** [comment]
Hmm, interesting. Let me give it a shot. This coming week will be busy. I will find some time for it.

**Comment by jwdonahue** [comment]
The examples tests passed on this windows run, but there were other failures:

https://github.com/maythamfahmi/CryptoNet/actions/runs/11420013912/job/31775239444

Here it passed on windows run, but failed on Ubuntu and MacOS:

https://github.com/maythamfahmi/CryptoNet/actions/runs/11420388609/job/31776037265

Error Message:
   System.ComponentModel.Win32Exception : Failed to start a process with file path 'AESExample.exe'. Target file or working directory doesn't exist, or the provided credentials are invalid.
  ----> System.ComponentModel.Win32Exception : An error occurred trying to start process 'AESExample.exe' with working directory '/tmp/AESExampleTests.AESExampleSmokeTest-076c44c6-1848-45bb-bd2f-ca9cd97e9418'. No such file or directory

Could be a permissions issue. Here's the code that created that path name:

```
    public static string CreateUniqueTempPathString(string prefix)
    {
        var result = Path.Combine(Path.GetTempPath(), prefix + Guid.NewGuid());

        return result;
    }
```
Shouldn't be anything wrong with that. `Path.GetTmpPath()` is portable, but my test is running the example using that temp directory as it's working directory. My *nix foo is weak these days, do we need to set permissions on that temp folder, to actually run an app in there? The binary is wherever the build or test system put all the bits, so that should be marked as executable and my test doesn't move any of those bits.

The build log output isn't much use. Not enough diagnostic output. I will try adding some Debug output to the unit tests and see if that shows up in the logs.

**Comment by jwdonahue** [comment]
Okay, confirmation that executable is missing in the Linux and MacOS environments. Not sure what the fix is or whether we should work-around it. For now, I'll limit the tests to Windows systems.

**Comment by jwdonahue** [comment]
We're green for now, but at least we get some coverage on Windows. I'll leave the Linux/MacOS build issues for to deal with.

**Comment by maythamfahmi** [comment]
there are good news. now ubuntu and mac os test without issues. The cause of the issue is that in windows an executable file has extention .exe, but in ubuntu and macos, the executable file does not .exe extention, I have added condition and all test does there job.

I will close #107, #108 and #117, we are back on track.
